# Beginner: Core Fundamentals

In [2]:
"""
    Checkerboard Matrix
"""

import numpy as np
def checker_board():
    """
       This functions creates an 8 x 8 matrix
       and nd fills it with a checkerboard pattern
       (0s and 1s) using slicing.
    """
    
    matrix = np.ones((8, 8))
    matrix[::2, ::2] = 0
    matrix[1::2, 1::2] = 0
    print(matrix)
checker_board()

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [3]:
"""
    This module contains a function used
    for normalization
"""

import numpy as np

def normalize():
    """
       This function creates a random 5 x 5 matrix
       and normalize it so all values are between 0 and 1
       (subtract the min and divide by the range).
    """

    matrix = np.random.randint(1, 20, size=(5, 5))
    matrix_min = matrix.min()
    matrix_max = matrix.max()
    matrix_range = matrix_max - matrix_min
    
    matrix = (matrix - matrix_min) / matrix_range

    print(matrix)

normalize()

[[0.76470588 1.         0.76470588 0.58823529 0.82352941]
 [0.05882353 0.58823529 0.64705882 0.76470588 0.41176471]
 [0.58823529 0.23529412 0.41176471 0.35294118 0.47058824]
 [0.47058824 0.         0.88235294 0.23529412 0.05882353]
 [0.41176471 1.         0.41176471 1.         0.94117647]]


In [4]:
"""
    This module contains a function that performs
    odd substitution using numpy
"""

def odd_substitution():
    """
        This function replaces all odd numbers
        in a 1D array of 1–10 with -1 without
        changing the original array
    """

    vector = np.arange(1, 11)
    print(np.where((vector % 2) != 0, -1, vector))

odd_substitution()

[-1  2 -1  4 -1  6 -1  8 -1 10]


# Intermediate: Data Manipulation

In [5]:
"""
   Module for a function that finds a common ground
"""

def find_common_ground():
    """
       Find the common items between two arrays
    """

    A = np.random.randint(1, 11, size=10)
    B = np.random.randint(3, 8, size=6)

    mask = np.isin(A, B)
    print(np.unique(A[mask]))
find_common_ground()


[5 6]


In [6]:
"""
   Module that contains a function called
   find missing values
"""

import numpy as np

def find_missing_values():
    """
       Create an array with random floats and insert np.nan
       at 5 random positions. Then, find the indices of
       these missing values.
    """

    vector = np.random.random(size=10)
    index = np.random.choice(vector.size, size=5, replace=False)

    vector[index] = np.nan
    print(index)
    
find_missing_values()

[9 5 7 1 2]


In [7]:
"""
   Module for a function called get_row_wise_means
"""

import numpy as np

def get_row_wise_means():
    """
         Create a 2D array and subtract the mean of each
         row from every element in that respective row.
    """

    matrix = np.random.randint(1, 20, size=(3, 4))
    mean_matrix = matrix.mean(axis=1, keepdims=True)

    print(matrix - mean_matrix)
get_row_wise_means()

[[ 2.25 -0.75  0.25 -1.75]
 [ 8.5  -3.5   2.5  -7.5 ]
 [ 3.75 -3.25  4.75 -5.25]]


# Advanced: Vectorization & Logic

In [8]:
"""
   Module for a function called
   one_hot_encoding
"""

import numpy as np

def one_hot_encoding():
    """
       Convert a 1D array of labels (like [0, 1, 2, 1, 0])
       into a one-hot encoded matrix
    """

    y_labels = np.array([0, 2, 1, 0])
    matrix = np.zeros((len(y_labels), y_labels.max() + 1), dtype='int64')
    x_labels = np.arange(matrix.shape[0])

    matrix[x_labels, y_labels] = 1

    print(matrix)
   
one_hot_encoding()

[[1 0 0]
 [0 0 1]
 [0 1 0]
 [1 0 0]]


In [9]:
"""
   This module contains a function for
   Euclidean distance
"""

import numpy as np

def calculate_euclidean_distance():
    """
       finds the straight-line distance between two arrays
    """

    p1 = np.array([1, 2, 3])
    p2 = np.array([4, 6, 8])

    result = np.linalg.norm(p2 - p1)
    print(result)
    
calculate_euclidean_distance()

7.0710678118654755


[ 7  3 12 10]
[ 7  3 12 10]
